export { isApplicative } from './applicative';
export { isApply } from './apply';
export { isChain } from './chain';
export { isComonad } from './comonad';
export { isExtend } from './extend';
export { isFilterable } from './filterable';
export { isFunctor } from './functor';
export { isMonoid } from './monoid';
export { isSemigroup } from './semigroup';
