name: Page
on:
  push:
    branches:
      - master
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Create Page
        run: |
          yarn docma

      - name: Checkout gh-page
        uses: actions/checkout@v2
        with:
          ref: gh-page
          clean: false

      - name: Publish page
        run: |
          rm -rf node_modules
          rsync -a -v site/ ./
          rm -rf site
          git config --global user.name 'ChimiDEV'
          git config --global user.email 'ChimiDEV@gmail.com'
          git add .
          git commit -m "CI: update page"
          git push
