name: Page
on:
  push:
    branches:
      - master
      - develop
      - feature/*
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: site/node_modules
          key: site/nodeModules-${{ hashFiles('**/site/yarn.lock') }}
          restore-keys: |
            site-nodeModules-

      - name: Install dependencies
        working-directory: site
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build Page
        working-directory: site
        run: yarn build

      - name: Deploy Page
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: site/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Publishing Page - {sha}: {msg}'
